# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#
substitutions:
  _ARTIFACTORY_SERVER_NAME: <servername>.jfrog.io
  _ARTIFACTORY_USER: <name>@<yourcompany>.com
  _ARTIFACTORY_PASSWORD: <password>
  _ARTIFACTORY_REPO_NAME: clouddays
  _JFROG_CLI_VERSION: 1.40.1

steps:
# Build the Cloud Builder Image that includes JFrog CLI
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=BASE_IMAGE=gcr.io/cloud-builders/npm'
  - '--build-arg=JFROG_CLI_VERSION=${_JFROG_CLI_VERSION}'
  - '--tag=${_ARTIFACTORY_SERVER_NAME}/${_ARTIFACTORY_REPO_NAME}/jfrog-cli:${_JFROG_CLI_VERSION}'
  - '.'
  wait_for: ['-']

# Tag a default builder version.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - '${_ARTIFACTORY_SERVER_NAME}/${_ARTIFACTORY_REPO_NAME}/jfrog-cli:${_JFROG_CLI_VERSION}'
  - '${_ARTIFACTORY_SERVER_NAME}/${_ARTIFACTORY_REPO_NAME}/jfrog-cli'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'login'
  - '${_ARTIFACTORY_SERVER_NAME}/${_ARTIFACTORY_REPO_NAME}/java-app'
  - '-u'
  - '${_ARTIFACTORY_USER}'
  - '-p'
  - '${_ARTIFACTORY_PASSWORD}'

images:
- '${_ARTIFACTORY_SERVER_NAME}/${_ARTIFACTORY_REPO_NAME}/jfrog-cli:${_JFROG_CLI_VERSION}'
- '${_ARTIFACTORY_SERVER_NAME}/${_ARTIFACTORY_REPO_NAME}/jfrog-cli'
tags: ['cloud-builders-community']
